version: '3.9'

services:
  db:
    image: mysql:8.1.0
    container_name: rails-db
    hostname: rails-db
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql 

  web:
    build: .
    container_name: rails-web
    volumes:
      - .:/rails
    ports:
      - 3000:3000
    depends_on:
      - db  
volumes:
  mysql_data: