name: Run RSpec Tests

on:
  push:
    branches:
      - master
      - github-actions

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306

    steps:

      # コードを取り出す
      - name: Checkout Repository
        uses: actions/checkout@v4

      # ruby環境の指定
      - name: Set up Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: replace config.yml
        run: cp config/database.yml.ci config/database.yml

      # bundle install
      - name: bundlerとライブラリのインストール
        run: |
          gem install bundler
          bundle install

      - name: shellの権限付与
        run: chmod +x ./bin/rails

      - name: dbのセッティング
        run: |
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:migrate RAILS_ENV=test

      # RSPECの実行
      - name: Run RSpec
        run: bundle exec rspec -o rspec_result.txt

      # 処理結果のアップロード
      - name: Upload Result
        uses: actions/upload-artifact@v3
        with:
          name: rspec-log 
          path: rspec_result.txt