name: Run RSpec Tests

on:
  push:
    branches:
      - master
      - github-actions

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        # GitHub ActionsでDockerを使用する際に、Dockerデーモンがホストとどのようにバインドされるかを指定する
        # docker:bind はDockerコンテナ内からDockerデーモンにアクセスするための設定
        # これにより、GitHub Actions内のDockerコンテナからDockerコマンドを実行できるようになりる
        image: docker:dind

    steps:

      # コードを取り出す
      - name: Checkout Repository
        uses: actions/checkout@v2

      # ruby, gemのインストール
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2 # またはプロジェクトに適したバージョン

      # bundle install
      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      # データベースとテーブルの作成
      - name: Setup database
        run: |
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:migrate RAILS_ENV=test

      # RSPECの実行
      - name: Run RSpec
        run: bundle exec rspec