name: Run RSpec Tests

on:
  push:
    branches:
      - master
      - github-actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # コードを取り出す
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: railsのシェルに権限を付与する
        run: sudo chmod +x ./bin/rails ./bin/docker-entrypoint

      # docker-compose.ymlの内容でコンテナ生成
      - name: Build and Run Containers
        run: sudo docker-compose up -d

      # RSPECの実行
      - name: Run RSpec
        run: sudo docker exec -t rails-web bundle rspec -o rspec_result.txt

      # 処理結果のアップロード
      - name: Upload Result
        uses: actions/upload-artifact@v3
        with:
          name: rspec-log 
          path: rspec_result.txt