name: Run RSpec Tests

on:
  push:
    branches:
      - master
      - github-actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # コードを取り出す
      - name: Checkout Repository
        uses: actions/checkout@v4

      # docker-compose.ymlの内容でコンテナ生成
      - name: Build and Run Containers
        run: docker-compose up -d

      # webコンテナにgemを入れる
      - name: bundle install
        run: docker exec rails-web bundle install

      # データベースの作成
      - name: Create database
        run: docker exec rails-web ./bin/rails db:create

      # テーブルの作成
      - name: Create Tables
        run: docker exec ./bin/rails db:migrate

      # RSPECの実行
      - name: Run RSpec
        run: docker exec rails-web bundle exec rspec