name: Run RSpec Tests

on:
  push:
    branches:
      - master
      - github-actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # コードを取り出す
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: sudo
        run: sudo chmod +x ./bin/rails

      # docker-compose.ymlの内容でコンテナ生成
      - name: Build and Run Containers
        run: sudo docker-compose up -d

      - name: bundle
        run: sudo docker-compose run bundle install

      - name: test
        run: sudo docker-compose run rails db:migrate

      # RSPECの実行
      - name: Run RSpec
        run: sudo docker exec rails-web bundle exec rspec